### ISSUE TITLE
响应式问题

### ISSUE THREAD

**Issue by DongGuoZheng** [Mrcxt/gridea-theme-lemon#5]
http://tva1.sinaimg.cn/large/0060lm7Tly1g5o12j9yurg30s80ho7wh.gif
缩放页面文章会溢出去，有的文章就没事，是我写文章格式有问题吗？还是主题的响应式问题？
![1](https://user-images.githubusercontent.com/28942554/62425090-b9b8de80-b709-11e9-9418-e93f28ab70bd.gif)

**Comment by Mrcxt** [comment]
应该是样式问题吧，我排查一下

**Comment by Mrcxt** [comment]
应该是样式问题吧，我排查一下

**Comment by DongGuoZheng** [comment]
> http://tva1.sinaimg.cn/large/0060lm7Tly1g5o12j9yurg30s80ho7wh.gif
> 缩放页面文章会溢出去，有的文章就没事，是我写文章格式有问题吗？还是主题的响应式问题？
> ![1](https://user-images.githubusercontent.com/28942554/62425090-b9b8de80-b709-11e9-9418-e93f28ab70bd.gif)
